### ISSUE TITLE
0 indexing on dominoes

### ISSUE THREAD

**Issue by pachewise** [abw333/dominoes#85]
it might be confusing to use 0-index on dominoes: Player nums are ok, but when displaying the dominoes it might be better to start w/ 1 (that way you can tell how many bones you have left by looking at the last one: 

1) [1|1]
2) [6|1]

**Comment by abw333** [comment]
I actually think it's better the way it is, for two reasons:

1. Currently, all of games, players, and dominoes are 0-indexed. The consistency is nice.
2. The target audience of this CLI consists of developers, who are used to working with 0-indexing. There's another project we could consider around building an actually nice web UI for playing dominoes.

Closing this issue for now, but feel free to reopen if you'd like to continue the discussion.
