### ISSUE TITLE
after first game, first player is asked "left or right" on first bone

### ISSUE THREAD

**Issue by pachewise** [abw333/dominoes#87]
Example:

It is now player 0's turn. Press enter to see player 0's hand.
Board:

Player 0's hand:
0) [1|1]
1) [1|3]
2) [2|6]
3) [3|4]
4) [0|4]
5) [1|4]
6) [6|6]
Choose which domino you would like to play: 6
Choose what end of the board you would like to play on (l or r): 

====
I would suggest simply detecting the empty board and skipping that Q.

**Comment by abw333** [comment]
I agree - will implement shortly.
